#!/bin/bash 
# 
# script to setup an client to be monitored by observium
# blindly taken from git://github.com/ghoulmann/observium-raspi-monitoring.git
#

community=public
location=home
contact=admin@localhost


#############################################################
# There should be no need to change anything below this line
#############################################################

DEBIAN=0
REDHAT=0
SUSE=0

# Check for root
LUID=$(id -u)
if [[ $LUID -ne 0 ]]; then
  echo "$0 must be run as root"
  exit 1
fi

# Get distro script for /usr/bin
if [ ! -x /usr/bin/distro ]; then
  wget http://www.observium.org/svn/observer/trunk/scripts/distro
  mv distro /usr/bin/distro
  chmod 755 /usr/bin/distro
fi

# figure out what distro we are on!
DISTRO=`/usr/bin/distro`
DISTRO=$(echo "$DISTRO" | awk '{print $1}')
if [ "$DISTRO" == "Ubuntu" -o "$DISTRO" == "Debian" ]; then
  DEBIAN=1
fi
if [ "$DISTRO" == "RedHat" -o "$DISTRO" == "CentOS" -o "$DISTRO" == "Mandriva" ]; then
  REDHAT=1
fi
if [ "$DISTRO" == "SUSE" ]; then
  SUSE=1
fi



# Install Function
install ()
{
  if [ $DEBIAN -eq 1 ]; then
    apt-get update 
    DEBIAN_FRONTEND=noninteractive apt-get -y \
      -o DPkg::Options::=--force-confdef \
      -o DPkg::Options::=--force-confold \
      install snmpd lm-sensors
  fi
  if [ $REDHAT -eq 1 ]; then
    yum --assumeyes install net-snmp net-snmp-utils
  fi
  if [ $SUSE -eq 1 ]; then
    echo "put install commands for SUSE here"
  fi

}

# Configure installed packages
configure ()
{
  if [ $DEBIAN -eq 1 ]; then
    # Configure /etc/default/snmpd
    sed -i "s|SNMPDOPTS='-Lsd -Lf /dev/null -u snmp -g snmp -I -smux -p /var/run/snmpd.pid'|SNMPDOPTS='-Lsd -Lf /dev/null -u snmp -p /var/run/snmpd.pid'|" /etc/default/snmpd

    # Configure snmpd.conf
    cat > /etc/snmp/snmpd.conf <<EOF
    com2sec readonly  default    $community
    group   MyROGroup v1         readonly
    group   MyROGroup v2c        readonly
    group   MyROGroup usm        readonly
    view    all       included  .1                               80
    access  MyROGroup ""         any       noauth    exact  all    none   none
    syslocation $location
    syscontact $contact
    #This line allows Observium to detect the host OS if the distro script is installed
    extend .1.3.6.1.4.1.2021.7890.1 distro /usr/bin/distro
EOF

  fi
  if [ $REDHAT -eq 1 ]; then
    # Configure /etc/sysconfig/snmpd
    echo "OPTIONS=\"-Lsd -Lf /dev/null -p /var/run/snmpd.pid\"" >> /etc/sysconfig/snmpd

    # Configure snmpd.conf
    cat > /etc/snmp/snmpd.conf <<EOF
    com2sec readonly  default    $community
    group   MyROGroup v1         readonly
    group   MyROGroup v2c        readonly
    group   MyROGroup usm        readonly
    view    all       included  .1                               80
    access  MyROGroup ""         any       noauth    exact  all    none   none
    syslocation $location
    syscontact $contact
    #This line allows Observium to detect the host OS if the distro script is installed
    extend .1.3.6.1.4.1.2021.7890.1 distro /usr/bin/distro
EOF

    # now, I need to open a hole in the firewall for snmp (port 161)
    RULENUM=$(iptables -n --list INPUT -v --line-numbers | grep REJECT | awk '{print $1}')
    # if iptables is running
    if [ "$RULENUM" != "" ]; then
      # add the rule
      iptables -I INPUT $RULENUM -p udp -m udp --dport 161 -j ACCEPT
      # make it persistent
      /etc/init.d/iptables save
    fi
    # make sure snmpd starts on boot
    chkconfig snmpd on

  fi
  if [ $SUSE -eq 1 ]; then
    echo "put configure commands for SUSE here"
  fi
}

# Start snmpd
startSNMPd ()
{
  if [ $DEBIAN -eq 1 ]; then
    /etc/init.d/snmpd restart
  fi
  if [ $REDHAT -eq 1 ]; then
    /etc/init.d/snmpd restart
  fi
  if [ $SUSE -eq 1 ]; then
    echo "put snmpd commands for SUSE here"
  fi
}

# Install packages
install 

# Configure packages
configure

# and restart snmpd
startSNMPd



