#!/bin/bash -ex

HOSTNAME=observium
USERNAME=observium
PASSWORD=observium
MYSQLUSER=observium
MYSQLPASSWORD=observium

# set hostname
echo "$HOSTNAME" > /etc/hostname
sed -i "s|127.0.1.1 \(.*\)|127.0.1.1 $HOSTNAME|" /etc/hosts

apt-get update
DEBIAN_FRONTEND=noninteractive apt-get -y \
    -o DPkg::Options::=--force-confdef \
    -o DPkg::Options::=--force-confold \
    install subversion

####################################################
# INSTALL OBSERVIUM
####################################################
mkdir -p /opt/observium 
cd /opt
svn co http://www.observium.org/svn/observer/trunk observium
cd observium

####################################################
# INSTALL DEPENDENCIES
####################################################
DEBIAN_FRONTEND=noninteractive apt-get -y \
    -o DPkg::Options::=--force-confdef \
    -o DPkg::Options::=--force-confold \
    install \
    libapache2-mod-php5 php5-cli php5-mysql \
    php5-gd php5-snmp php-pear snmp graphviz \
    mysql-server mysql-client rrdtool \
    fping imagemagick whois mtr-tiny nmap ipmitool \
    libvirt-bin

mysqladmin -u root password $MYSQLPASSWORD

####################################################
# INSTALL IPv4/IPv6 pear libraries
####################################################
pear install Net_IPv4
pear install Net_IPv6

####################################################
# CONFIGURE OBSERVIUM
####################################################
cp config.php.default config.php
sed -i "s|USERNAME|$MYSQLUSER|" config.php
sed -i "s|PASSWORD|$MYSQLPASSWORD|" config.php
mkdir graphs rrd
chown www-data:www-data graphs rrd

mysql -u root -p$MYSQLPASSWORD -e "create database observium;"
mysql -u root -p$MYSQLPASSWORD -e "grant all privileges on observium.* to '$MYSQLUSER'@'localhost' identified by '$MYSQLPASSWORD';"

php includes/update/update.php


####################################################
# Final tasks
####################################################
a2enmod rewrite
# apache2ctl restart

./adduser.php $USERNAME $PASSWORD 10

# Create the service file
echo "Observium:      http://\$ipaddr"            > /etc/confconsole/services.txt
echo "Web Shell:      http://\$ipaddr:12320"     >> /etc/confconsole/services.txt
echo "Webmin:         http://\$ipaddr:12321"     >> /etc/confconsole/services.txt
echo >> /etc/confconsole/services.txt
echo "   Note: Default userid/password for Observium is:"  >> /etc/confconsole/services.txt
echo "         observium/observium" >> /etc/confconsole/services.txt


service mysql stop
service apache2 stop

####################################################
# done!
####################################################
exit




