#!/bin/bash -ex

DB_NAME=observium
DB_USER=observium
DB_PASS=$(mcookie)

USERNAME=observium
PASSWORD=observium

SRC=/usr/local/src
APPROOT=/opt/observium

# unpack observium
tar -zxf $SRC/observium-*.tar.gz -C $(dirname $APPROOT)
rm $SRC/observium-*.tar.gz

# start services
/etc/init.d/mysql start

# setup the database
CONF=$APPROOT/config.php
cp $APPROOT/config.php.default $CONF
sed -i "s|db_name.*|db_name'] = \"$DB_NAME\";|" $CONF
sed -i "s|db_user.*|db_user'] = \"$DB_USER\";|" $CONF
sed -i "s|db_pass.*|db_pass'] = \"$DB_PASS\";|" $CONF

MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

php $APPROOT/includes/update/update.php

####################################################
# INSTALL IPv4/IPv6 pear libraries
####################################################
pear install Net_IPv4
pear install Net_IPv6

####################################################
# CONFIGURE OBSERVIUM
####################################################
cd $APPROOT
mkdir graphs rrd
chown www-data:www-data graphs rrd

####################################################
# Final tasks
####################################################
a2enmod rewrite
# apache2ctl restart

./adduser.php $USERNAME $PASSWORD 10

# Create the service file
echo "Observium:      http://\$ipaddr"            > /etc/confconsole/services.txt
echo "Web Shell:      http://\$ipaddr:12320"     >> /etc/confconsole/services.txt
echo "Webmin:         http://\$ipaddr:12321"     >> /etc/confconsole/services.txt
echo >> /etc/confconsole/services.txt
echo "   Note: Default userid/password for Observium is:"  >> /etc/confconsole/services.txt
echo "         observium/observium" >> /etc/confconsole/services.txt

# stop services
/etc/init.d/mysql stop

