#!/bin/bash -ex

DB_NAME=observium
DB_USER=observium
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey

SRC=/usr/local/src
APPROOT=/opt/observium
WEBROOT=/var/www/observium

# unpack observium and create required directories
tar -zxf $SRC/observium-*.tar.gz -C $(dirname $APPROOT)
rm $SRC/observium-*.tar.gz

mkdir -p $APPROOT/rrd
mkdir -p $APPROOT/graphs
chown www-data:www-data $APPROOT/rrd
chown www-data:www-data $APPROOT/graphs

# configure apache and webroot
a2dissite 000-default
a2ensite observium
a2enmod rewrite

ln -s $APPROOT/html $WEBROOT

# start services
service mysql start

# setup the database
CONF=$APPROOT/config.php
cp $APPROOT/config.php.default $CONF
sed -i "\
    s|\(\['db_name'\]\).*|\1 = \"$DB_NAME\";|; \
    s|\(\['db_user'\]\).*|\1 = \"$DB_USER\";|; \
    s|\(\['db_pass'\]\).*|\1 = \"$DB_PASS\";|; " $CONF

echo "\$config['email']['backend'] = \"sendmail\";" >> $CONF
echo "\$config['email']['sendmail_path'] = \"/usr/bin/sendmail -t -i\";" >> $CONF

MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# insert default schema
cd $APPROOT
./discovery.php -u

# create admin user (level 10)
$APPROOT/adduser.php $ADMIN_NAME $ADMIN_PASS 10

# configure snmp mibs
echo "mibdirs /opt/observium/mibs" > /etc/snmp/snmp.conf

# install pear libraries
pear install Net_IPv4
pear install Net_IPv6

# allow logging
mkdir -p $APPROOT/logs
chown -R www-data:www-data $APPROOT/logs
ln -s $APPROOT/logs /var/log/observium

# stop services
service mysql stop

