#!/bin/bash -e
# regenerate observium secrets and mysql password

. /etc/default/inithooks

CONF=/opt/observium/config.php

PASSWORD=$(mcookie)

sed -i "s/\(\$config\['db_pass'] =\) .*;$/\1 \"$PASSWORD\";/" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=observium --pass="$PASSWORD"
